# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-03 19:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('mail', models.EmailField(max_length=254)),
                ('day', models.DateTimeField(default=datetime.datetime.today)),
            ],
        ),
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField(max_length=400)),
            ],
        ),
        migrations.AddField(
            model_name='bday',
            name='msg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='birthday.message'),
        ),
    ]
