# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-03 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bday',
            options={'verbose_name': 'Registro de cumpleaño', 'verbose_name_plural': 'Registros de cumpleaños'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Mensaje de cumpleaño', 'verbose_name_plural': 'Mensajes de cumpleaños'},
        ),
        migrations.AlterField(
            model_name='bday',
            name='mail',
            field=models.EmailField(max_length=254, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='bday',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='message',
            name='msg',
            field=models.TextField(max_length=400, verbose_name='Mensaje'),
        ),
    ]
