# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-03 19:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0002_auto_20180403_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bday',
            name='day',
            field=models.DateTimeField(default=datetime.datetime.today, verbose_name='Fecha de cumpleaño'),
        ),
        migrations.AlterField(
            model_name='bday',
            name='msg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='birthday.message', verbose_name='Mensaje'),
        ),
    ]
