# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-04 14:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0003_auto_20180403_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='birthday_day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('bday', models.DateTimeField(default=datetime.datetime.today, verbose_name='Fecha de cumpleaño')),
            ],
            options={
                'verbose_name': 'Registro de cumpleaño',
                'verbose_name_plural': 'Registros de cumpleaños',
            },
        ),
        migrations.RenameModel(
            old_name='message',
            new_name='birthday_message',
        ),
        migrations.RemoveField(
            model_name='bday',
            name='msg',
        ),
        migrations.DeleteModel(
            name='bDay',
        ),
        migrations.AddField(
            model_name='birthday_day',
            name='msg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='birthday.birthday_message', verbose_name='Mensaje'),
        ),
    ]
